### ISSUE TITLE
plot heatmaps

### ISSUE THREAD

**Issue by zhoudreames** [glogsdon1/sunk-based_assembly#3]

**Comment by glogsdon1** [comment]
Hi zhoudreames, 

We have an interactive browser tool for this now, developed by Mitchell Vollger and Peter Kerpedjiev. Here's the CHM13 chr8 centromere: https://resgen.io/viewer/C0j8MYBMQVyxXT1wHLqv_w. You could reach out to Mitchell directly if you need the raw code (mvollger@uw.edu).

**Comment by zhoudreames** [comment]
thank ~
