### ISSUE TITLE
PFGE Southern blotting

### ISSUE THREAD

**Issue by zhoudreames** [glogsdon1/sunk-based_assembly#7]
in your article ,the centromere was valiated by PFGE Southern blotting.I asked you Which company did this experiment in? we want to do this experiment for my project in the future,thanks~

**Comment by zhoudreames** [comment]
@glogsdon1

**Comment by glogsdon1** [comment]
Hi zhoudreames, 

The PFG Southern blot was done by Mikhail Liskovykh in the Larionov lab at the NCI. He's very skilled, and we were lucky to have him as part of the project!

To see how others contributed, you can check out the "Contributions" section of the paper (shown below for convenience):
G.A.L. and E.E.E. conceived the project; G.A.L., K.H., K.M.M., A.M.L., C.B. and M.S. generated long-read sequencing data; G.A.L., M.R.V., P.H., Y.M., S.K., S.N., P.C.D., A.R., T.D., D.P., W.T.H., A.M., A.V.B., M.K., T.A.G.-L., C.J., S.C.M., K.H.M. and A.M.P. analysed sequencing data, created genome assemblies, and performed quality control analyses; G.A.L., M.R.V., S.K., A.M.P. and S.N. finalized the chromosome 8 assembly; G.A.L., S.K., S.N., A.M., A.V.B. and K.H.M. assessed the assembly of the centromere; M.A.L. generated pulsed-field gel Southern blots; G.A.L., L.M. and M.V. generated microscopy data; L.G.D. generated and analysed droplet digital PCR data; U.S. provided the CHM13 cell line; J.L.G. and V.L. supervised experimental analyses; G.A.L., M.R.V., D.P. and E.E.E. developed the figures; and G.A.L. and E.E.E. drafted the manuscript.

**Comment by zhoudreames** [comment]
Do you have his email address? thanks~
